#
# FILE NAME:    Makefile
# 
# DESCRIPTION:  Makefile for matrix_math
#
# PURPOSE:	Build an executable Program
#
# MODIFICATION HISTORY:
#
# Author 	Date		Modification(s)
# ---------------------------------------------
# Samuel Ayeju   2018-04-30	Version 1.0
# ---------------------------------------------

#	This is our original generic makefile command that will build
#	any stand alone ".cpp" source file
#	Usage: make matrix_math

.cpp : 
	g++ -o $* $*.cpp -std=c++11

matrix_math: Matrix.cpp Matrix.h

